### PR TITLE
Publish to Github Pages directly using Github Actions

### PR DESCRIPTION
**Pull request by Xmader**
The https://github.com/LibreScore/librescore.github.io repo can now be sunset

### CODE REVIEW

**Comment by Xmader** [comment]
Assigning a Custom domain (currently [webmscore-pwa.librescore.org](https://webmscore-pwa.librescore.org/)) on this repo is required because urls in [index.html](https://github.com/LibreScore/librescore.github.io/blob/901800d/index.html) are all using absolute paths.

**Comment by PeterNjeim** [comment]
I'll merge it but I'll keep librescore.github.io alive anyways for people who already installed it as a PWA

**Comment by PeterNjeim** [comment]
I also recommend changing it to `https://webmscore.librescore.org`

**Comment by Xmader** [comment]
I was thinking to reserve `https://webmscore.librescore.org` for whatever docs for https://github.com/LibreScore/webmscore. ~~I really don't know which approach is better.~~
We could always redirect `webmscore.librescore.org` to `webmscore-pwa.librescore.org`, but if I want to, for example, add interactive docs for `LibreScore/webmscore` on `webmscore.librescore.org`, it's not easy for the pwa to migrate to a new domain name.

**Comment by Xmader** [comment]
I redirected `webmscore.librescore.org` to [webmscore-pwa.librescore.org](https://webmscore-pwa.librescore.org/)

(Using [HTTP 307 Temporary Redirect](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307))

**Pull request merged**
